# Cron Dockerfile
FROM python:3.9

# Install required packages
RUN apt-get update && apt-get install -y cron curl

# Set working directory
WORKDIR /code

# Copy the entrypoint script for cron setup
COPY cron_entrypoint.sh /entrypoint.sh

# Define the entrypoint for cron
ENTRYPOINT ["/bin/sh", "-c", "chmod +x /entrypoint.sh /; exec /entrypoint.sh"]
