# Generated by Django 4.2.11 on 2024-05-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "category_label",
                    models.TextField(primary_key=True, serialize=False, unique=True),
                ),
                ("category_id", models.TextField()),
                ("category_code", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment_user", models.TextField()),
                ("comment_text", models.TextField()),
                ("comment_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                ("content_id", models.AutoField(primary_key=True, serialize=False)),
                ("content_source_id", models.TextField()),
                ("content_headline", models.TextField(unique=True)),
                ("content_source", models.TextField()),
                ("content_url", models.TextField()),
                ("content_category", models.TextField()),
                ("content_text", models.TextField()),
                ("content_image", models.TextField()),
                ("content_date", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("source_id", models.AutoField(primary_key=True, serialize=False)),
                ("source_url", models.URLField(default="")),
                ("source_trust_rating", models.IntegerField(default=0)),
                ("source_name", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                ("thread_id", models.AutoField(primary_key=True, serialize=False)),
                ("content_id", models.IntegerField()),
                ("content_title", models.TextField()),
                ("thread_response", models.TextField(max_length=300)),
            ],
        ),
    ]
