# Generated by Django 4.0.5 on 2024-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_source_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='thread',
            name='content_id',
            field=models.TextField(),
        ),
    ]
