# Generated by Django 4.0.5 on 2024-04-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_category_category_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_label',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
