# Generated by Django 4.0.5 on 2024-04-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_headline',
            field=models.TextField(unique=True),
        ),
    ]
